# Generated by Django 4.2.30 on 2026-08-20 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='El ISBN debe contener 10 o 13 digitos validos', regex='^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)')]),
        ),
    ]
